application: pure-spring-568
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /
  static_files: static/index.html
  upload: static/*

- url: /static/
  static_dir: static/

- url: .*
  script: _go_app

# REMOVE BEFORE DEPLOYING
default_expiration: "1m"
