application: pure-spring-568
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/*

- url: /
  static_files: static/index.html
  upload: static/*

- url: /pledge
  static_files: static/pledge.html
  upload: static/*



- url: /static/
  static_dir: static/

- url: .*
  script: main.app

# REMOVE BEFORE DEPLOYING
default_expiration: "1m"
libraries:
- name: ssl
  version: latest
